config/routes.rb
Rails.application.routes.draw do
  get "chats/index"
  get "chats/create"
  get "room/index"
  # Routes pour les utilisateurs via Devise
  devise_for :users, controllers: { registrations: "users/registrations" }

  post "presence/disconnected", to: "presence#disconnected"

  # Définition des routes pour Room (les salles)
  resources :rooms
  resources :chats

  resources :rooms do
    member do
      post :join
      post :join_as_spectator
      post :submit_join_form
      get :play
      get :show
      get :select_role
    end
  end



  namespace :api do
    namespace :v1 do
      get "join_room/fetch_instruments/:slot_type_id", to: "join_room#fetch_instruments"
    end
  end

  # config/routes.rb
  Rails.application.routes.draw do
  get "chats/index"
  get "chats/create"
    resources :rooms, only: [:show] do
      member do
        get "join"  # Pour la fonction de récupération des informations de la salle
        post "submit_join_form"  # Pour soumettre le formulaire
      end
    end
  end




  post "join", to: "rooms#join"

  # Autres routes de l'application
  get "up" => "rails/health#show", as: :rails_health_check

  # Route racine (optionnelle)
  root "rooms#index"
end

app/views/layouts/_navbar.html.erb
<nav class="bg-white flex border-gray-200 dark:bg-gray-900"> <div class="flex items-center justify-between w-full p-4">
   <%= link_to 'Accueil', root_path, class: "flex items-center space-x-3 rtl:space-x-reverse font-semibold whitespace-nowrap dark:text-white" %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if !user_session %>
          <li>
            <%= link_to 'Se Connecter', user_session_path, class:"block py-2 px-3 rounded text-white" %>
          </li>
          <li>
            <%= link_to "S'inscrire", new_user_registration_path, class:"block py-2 px-3 rounded text-blue-500" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Créer un salon', new_room_path, class:"block py-2 px-3 rounded text-white" %>
          </li>
          <li>
            <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"cursor-pointer block py-2 px-3 text-white rounded text-red-600 "%>
          </li>
          <li>
            <%= link_to "Chat", chats_path, class:"block py-2 px-3 rounded text-purple-500" %>
          </li>
      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Jam Together React" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body class="bg-stone-700 flex-row">
   
      <%= render 'layouts/navbar' %>
   
  <main class="container mx-auto px-5">
    <% flash.each do |key, value| %>
      <div class="relative top-15 right-1/2 mt-2 z-40 <%= key == 'notice' ? 'success' : 'danger' %>" role="alert" id="fade-out">
        <span class="block sm:inline"><%= value %></span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title></svg>
          </span>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>